import type { Metadata } from "next";
import { Nunito, Pacifico } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  subsets: ["vietnamese"],
  variable: "--font-nunito",
});

const pacifico = Pacifico({
  subsets: ["vietnamese"],
  weight: "400",
  variable: "--font-pacifico",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} ${pacifico.variable}`}>
        {children}
      </body>
    </html>
  );
}
